feat: Implement useCopyToClipboard hook
react-hookz/web pull request #883
Opened 2022-07-22 19:09 UTC by pbellon

## What new hook does?
New hook inspired by react-use's `useCopyToClipboard`, copies some text to clipboard. It provides a state that reflects copy process and 2 callbacks:
- `copyToClipboard`, main callback to copy some data into clipboard
- `resetCopyState`, new callback not present in react-use's implementation to easily reset `copyState` to initial value (all fields undefined)

Countrary to react-use's implementation, this hook does not rely on `copy-to-clipboard` external dependency. Instead it simply uses navigator.clipboard API which seems to have good support on major browser vendors see [caniuse][https://caniuse.com/?search=navigator.clipboard.]. Because of this, the `noUserInteraction: boolean` has been removed from `copyState`. 

Also added a `success: boolean` field in `copyState` to ease usage but this is up to debate since we could do as react-use's implementation and only rely on `value` not being undefined.

## Checklist

- [x] Have you read [contribution guideline](../../CONTRIBUTING.md)?
- [ ] Does the code have comments in hard-to-understand areas?
- [x] Is there an existing issue for this PR?
  - #33 (useCopyToClipboard)
- [x] Have the files been linted and formatted?
- [x] Have the docs been updated?
- [x] Have the tests been added to cover new hook?
- [x] Have you run the tests locally to confirm they pass?

2022-08-08 00:48 UTC, xobotyi requested changes
1) due to component lack of clipboard read - i really dont seee the need in state at all.

    IMO there is only need in returned callback that returns copied text or throw an error in case of any. Current Implementation will lead to unnecessary re-renders, as of my experience - i never dont care what been copied - most of the time it is simple success or error message depending on results.
    
    So i'd suggest simplifying the hook, but threfore component would be redundant, as it han be replaced with single function.
  
    Instead of that i can suggest reimplementing this hook as more complex hook `useClipboard` that will give access to clipboard reads and reaction to [clipboard events occured on docment](https://developer.mozilla.org/en-US/docs/Web/API/ClipboardEvent), events list can be configurable for hook to provide maximal granularity of configuration.

2) clipboard reset and clipboard set can be merged into single function - do reset when `undefined` received.

3) copy function can receive any value, as there are loads of stringable objects that are not strings, just perform `String(val)` before passing to clipboard.

4) you did not provide any jsdoc for hook, as it is required by contribution guide.

2022-10-06 05:05 UTC, ArttuOll commented
Is this new hook, `useClipboard`, being worked on by anyone at the moment? If not, I could start implementing it over the weekend.

2022-10-09 11:15 UTC, xobotyi commented
@ArttuOll you can take and fix my remarks

2023-01-02 21:13 UTC, xobotyi commented
@ArttuOll next pick this one when you'll have free time🍻

2023-01-07 14:00 UTC, ArttuOll commented
@xobotyi I'm currently sketching the API for `useClipboard`. What do you think about this?

## Return

- **eventHandlers**
    - **onCopy** _`(event: ClipboardEvent) => void`_ - Event handler for the `copy` event.
    - **onCut** _`(event: ClipboardEvent) => void`_ - Event handler for the `cut` event.
    - **onPaste** _`(event: ClipboardEvent) => void`_ - Event handler for the `paste` event.
- **setClipboardContent** _`(content: unknown) => void`_ - Populate the clipboard with `content`.

2023-01-08 12:58 UTC, xobotyi commented
im not sure about returned event handlers - i think usage of [ClipboardAPI](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API) would be better approach

2023-01-08 15:01 UTC, ArttuOll commented
> im not sure about returned event handlers - i think usage of [ClipboardAPI](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API) would be better approach

You mean something like exposing `readText` and `writeText` from `navigato.clipboard` through the hook?

2023-01-08 16:15 UTC, xobotyi commented
and ways to assign clipboard events handlers, yes.

2023-01-09 17:15 UTC, ArttuOll commented
How about this?

## Return

- **eventHandlers**
    - **onCopy** _`(event: ClipboardEvent) => void`_ - Event handler for the `copy` event.
    - **onCut** _`(event: ClipboardEvent) => void`_ - Event handler for the `cut` event.
    - **onPaste** _`(event: ClipboardEvent) => void`_ - Event handler for the `paste` event.
- **setClipboardContent** _`(content: unknown) => void`_ - Populate the clipboard with `content`.
- **readClipboardContent** _`() => Promise<string>`_ - Read clipboard content
- - -
> and ways to assign clipboard events handlers

I'm confused about this. Does **eventHandlers** not already cover all the possible clipboard events?

Also, should we go with `readText` and support only string data or with `read` with supports non-text content, but isn't supported by Firefox? I would probably go with just `readText`, because `read` seems to be too bleeding edge.

2023-01-14 12:35 UTC, ArttuOll commented
Rethinking this now, I think I'll start implementing something like this. We can change it when I submit a PR, if we need to.

## Return
- **write** _`(newClipText: string, onSuccess: () => void, onFailure: () => void ) => void`_ - Write text to the clipboard.
- **read** _`(onSuccess: (clipText: string) => void, onFailure: () => void ) => void`_ - Read text from the clipboard.

2023-01-18 08:16 UTC, xobotyi commented
Yes =)
Sorry for long response - been really loadded at work recently.

This is exactly what i've been concerned of - you rprevious aproach offered callbacks that should be passed to desired element what is not necessary needed.

The only concern now - it seems no possbility to somehow validate\filter the target when we're dealing with clipboard, at least im not able to see it in offered signature.

2023-05-14 08:47 UTC, xobotyi commented
Given this more thinking lately.
Do we even need this hook? 

Previously such hook been needed due to poor spreading of clipboad api and usage of third-party libs, which is not the case nowadays.
Usually such hook used to copy something to user's clipboard therefore there is no need for state updates since application know the state in advance.

I think i'd vote ditching that hook and add note to migration guide. WEB-API covering whole functionality by itself wouthout need of custom hook.

2023-05-16 04:45 UTC, ArttuOll commented
> Given this more thinking lately. Do we even need this hook?
> 
> Previously such hook been needed due to poor spreading of clipboad api and usage of third-party libs, which is not the case nowadays. Usually such hook used to copy something to user's clipboard therefore there is no need for state updates since application know the state in advance.
> 
> @JoeDuncko @ArttuOll I think i'd vote ditching that hook and add note to migration guide. WEB-API covering whole functionality by itself wouthout need of custom hook.

This is pretty much what I thought when I started implementing this. The hook would do pretty much nothing of value, so the hook is unnecessary in my opinion also.

2023-05-17 07:18 UTC, closed without merging

2023-05-21 02:37 UTC, JoeDuncko commented
> > Given this more thinking lately. Do we even need this hook?
> > Previously such hook been needed due to poor spreading of clipboad api and usage of third-party libs, which is not the case nowadays. Usually such hook used to copy something to user's clipboard therefore there is no need for state updates since application know the state in advance.
> > @JoeDuncko @ArttuOll I think i'd vote ditching that hook and add note to migration guide. WEB-API covering whole functionality by itself wouthout need of custom hook.
> 
> This is pretty much what I thought when I started implementing this. The hook would do pretty much nothing of value, so the hook is unnecessary in my opinion also.

Sorry for the delay. I agree.