Add useRendersCount hook
react-hookz/web pull request #990
Opened 2022-10-25 20:00 UTC by ChloeMouret

## What new hook does?

useRendersCount tracks component's renders count including the first render.

## Checklist

- [X] Have you read [contribution guideline](../../CONTRIBUTING.md)?
- [X] Have the files been linted and formatted?
- [X] Have the docs been updated?
- [X] Have the tests been added to cover new hook?
- [X] Have you run the tests locally to confirm they pass?

2022-10-27 16:39 UTC, xobotyi requested changes
1) You havent updated `README.md`
2) `index.ts` is missing reexport of this hook
3) You should add note within [migrating-from-react-use.story.mdx](https://github.com/react-hookz/web/blob/master/src/__docs__/migrating-from-react-use.story.mdx)

2022-10-27 16:39 UTC, xobotyi commented on src/useRendersCount/__docs__/example.stories.tsx
> +  const [count, setCount] = useState(0);
Better to use `useRerender` hook.

In our examples we're trying to reuse our hooks as much as possible.

2022-10-27 18:14 UTC, ArttuOll commented on src/useRendersCount/__tests__/dom.ts
> +  });
This test is unnecessary, since TypeScript guarantees that a number is returned.

2022-11-19 14:09 UTC, ArttuOll approved these changes
Pushed a couple of typo fixes, otherwise looks good to me!

2022-11-20 15:25 UTC, merged

2022-11-20 15:30 UTC, xobotyi commented
:tada: This PR is included in version 19.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@react-hookz/web/v/19.2.0)
- [GitHub release](https://github.com/react-hookz/web/releases/tag/v19.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: